require("indent_blankline").setup({
	char = "│",
	show_first_indent_level = true,
	filetype_exclude = {
		"", -- for all buffers without a file type
		"NvimTree",
		"TelescopePrompt",
		"dashboard",
		"dotooagenda",
		"flutterToolsOutline",
		"fugitive",
		"git",
		"gitcommit",
		"help",
		"json",
		"log",
		"markdown",
		"peekaboo",
		"startify",
		"todoist",
		"txt",
		"text",
		"vimwiki",
		"vista",
	},
	buftype_exclude = { "terminal", "nofile" },
	show_trailing_blankline_indent = false,
	show_current_context = true,
	context_patterns = {
		"class",
		"function",
		"method",
		"block",
		"list_literal",
		"selector",
		"^if",
		"^table",
		"if_statement",
		"while",
		"for",
		"type",
		"var",
		"import",
	},
	space_char_blankline = " ",
})
