require("legendary").setup({
	which_key = {
		auto_register = true,
		do_binding = false,
	},
	scratchpad = {
		view = "float",
		results_view = "float",
		float_border = "double",
		keep_contents = true,
	},
})

require("which-key").register({
	["<leader>"] = {
		d = {
			name = "Dap commands",
			b = "debug: Toggle breakpoint",
			d = "debug: Terminate debug session",
			r = "debug: Continue",
			l = "debug: Open repl",
			i = "debug: Step in",
			o = "debug: Step out",
			v = "debug: Step over",
		},
		f = {
			name = "Telescope commands",
			p = "find: Project",
			w = "find: Word",
			r = "find: File by frecency",
			e = "find: File by history",
			c = "ui: Change color scheme",
			z = "edit: Change current directory by zoxide",
			f = "find: File under current work directory",
			g = "find: File under current git directory",
			n = "edit: New file",
		},
		h = {
			name = "Gitsigns commands",
			b = "git: Blame line",
			p = "git: Preview hunk",
			s = "git: Stage hunk",
			u = "git: Undo stage hunk",
			r = "git: Reset hunk",
			R = "git: Reset buffer",
		},
		l = {
			name = "LSP commands",
			i = "lsp: LSP Info",
			r = "lsp: LSP Restart",
			t = "lsp: OutlineToggle",
		},
		n = {
			name = "NvimTree commands",
			f = "filetree: NvimTree find file",
			r = "filetree: NvimTree refresh",
		},
		p = {
			name = "Packer commands",
			s = "packer: PackerSync",
			c = "packer: PackerCompile",
			t = "packer: PackerStatus",
		},
		t = {
			name = "Trouble commands",
			t = "trouble: Toggle",
			r = "trouble: LSP References",
			d = "trouble: Show document diagnostics",
			w = "trouble: Show workspace diagnostics",
			q = "trouble: Show quickfix list",
			l = "trouble: Show loclist",
		},
		["="] = "dial: Increment(Cycle)",
		["-"] = "dial: Decrement(Cycle)",
		["lg"] = "git: Show lazygit",
	},
	["g"] = {
		["["] = "lsp: Goto prev diagnostic",
		["]"] = "lsp: Goto next diagnostic",
		a = "lsp: Code action",
		d = "lsp: Preview definition",
		D = "lsp: Goto definition",
		h = "lsp: Show definition and references",
		r = "lsp: Rename",
		S = "lsp: Signature help",
		["DC"] = "lsp: Declaration",
		I = "lsp: Implementation",
		T = "lsp: Type definition",
		["DL"] = "lsp: Show loclist",
		["QL"] = "lsp: Show quickfix list",
		--- nvim-surround
		z = "surround: Add surround",
		Z = "surround: Add surround around line",
		["zd"] = "surround: Delete surround",
		["zc"] = "surround: Change surround",
	},
	["<leader>dv"] = "git: Show diff",
	["<leader><leader>dv"] = "git: Close diff",
	["K"] = "lsp: Hover doc",
	["<C-n>"] = "filetree: NvimTree toggle sidebar",
})
