blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/CharlesChiuGit/nvimdots.lua/discussions
    about: Any issue that does not fall into the above categories shall go here.
  - name: GitHub Wiki
    url: https://github.com/CharlesChiuGit/nvimdots.lua/wiki
    about: Make sure you have checked our documentation first. To be explicit, the "Issues" section.
