blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/CharlesChiuGit/nvimdots.lua/discussions
    about: When you have questions that are not bug reports or feature requests
  - name: GitHub Wiki
    url: https://github.com/CharlesChiuGit/nvimdots.lua/wiki
    about: Make sure you have check our documentation first, to be explicite, the `FAQ`.
